# Generated by Django 4.2 on 2026-08-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('hotel_type', models.CharField(choices=[('Luxury', 'Luxury'), ('Budget', 'Budget'), ('Resort', 'Resort'), ('Business', 'Business')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='hotel_images/')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_rooms', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
